version: '3'
services:
  swagger_app:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - 5000:5000
      - 8000:8000
      - 8080:8080
    volumes:
      - ./..:/opt/app
    command: /bin/bash
    stdin_open: true
    tty: true
