version: '3'

services:
  mongodb:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    image: bdapidb
    
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data/db:/data/db
  python:
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile
    image: evepython
    depends_on: 
      - mongodb
    ports:
      - 5000:5000
      - 8000:8000
    volumes:
      - ./..:/opt/eve
    command: /bin/bash
    stdin_open: true
    tty: true
    links:
      - mongodb
